# -*- coding: utf-8 -*-
"""numpy practice.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wewvx2m0hxTVP0R2hVXCHSxrJOvxBfBI
"""

import numpy as mpy

a=mpy.array([2,7,1,45,9])

type(a)

c=mpy.array([82,57,15,45,94])

a

c

a[0]

a[-1]

a[-2]

a+c

a+2

a**2

p=mpy.array([[2,4,43,4],[2,5,3,54],[1,23,34,23]])

p

p[2]

p[1][2]

p[0-2][1]

p*2

p[-1][-1]

z=mpy.array([[2,7],[3,8],[2,9],[9,4]])

z

z.shape

p.shape

z[0:2]

z[0:,[0]]

z[0:,1]

p

p[0:,[1]]

p[0:,[0,2]]

z[[0,3],1]

z[1:,[0,1]]

p

p.reshape(4,3)

p.reshape(6,2)

mpy.zeros((3,2))

mpy.full((3,4),6)

dir(mpy)

import matplotlib

