# -*- coding: utf-8 -*-
"""piechartstudent.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jUqP4l_7fa-AwvANu99eXXHuiEMyfwjS
"""

import matplotlib.pyplot as plt
import pandas as pd
# reading data from csv file
df=pd.read_csv('student.csv')
# student_name=df["Student_Name"]
marks=df["marks"]
# show pie chart of marks of student
p=plt.pie(marks,labels=df["Student_Name"],explode=(0.1,0,0,0,0),startangle=70,
autopct='%1.1f%%')