# -*- coding: utf-8 -*-
"""Task1ML.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PoC10rledjZBcHFAtceSiA1weoZE-tBn
"""

import numpy as np
# take input dimension of 2d array
m=int(input("Enter no. of rows : "))
n=int(input("Enter no. of column : "))
# input random number b/w 0 , 100 
p=np.random.randint(100,high=None,size=(m,n))

# Store array in a csv file named new_file.csv
with open("new_file.csv","w+") as my_csv:
    csvWriter = csv.writer(my_csv,delimiter=',')
    csvWriter.writerows(p)

import pandas as pd

pd.read_csv('new_file.csv')

